import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

const root=path.resolve(import.meta.dirname,'..');
const app=fs.readFileSync(path.join(root,'app.js'),'utf8');
const account=fs.readFileSync(path.join(root,'ai-account.js'),'utf8');
const backend=fs.readFileSync(path.join(root,'supabase/functions/phone-ai/index.ts'),'utf8');
const setup=fs.readFileSync(path.join(root,'AI_BACKEND_SETUP.md'),'utf8');

assert.match(app,/function aiImageRelayOn\(\)\{return !!\(aiImageInit\(\)\.enabled&&aiCoreUrl\(\)\);\}/);
assert.match(app,/if\(aiImageRelayOn\(\)\)\{const d=await aiRelay\('image'/);
assert.match(app,/function imageGenerationAvailable\(\)/);
assert.doesNotMatch(app,/if\(aiCoreOn\(\)\)\{const d=await aiRelay\('image'/);
assert.match(app,/function imageGenerateExternal\(base,key,model,prompt,size\)/);
assert.match(app,/const urls=\/\\\/v1\$\/i\.test\(b\)\?\[b\+path\]:\[b\+'\/v1'\+path,b\+path\]/);
assert.match(app,/接口返回网页HTML，不是API JSON/);
assert.match(app,/function imageCollectValues\(v,out\)/);
assert.match(app,/inlineData&&v\.inlineData\.data/);
assert.match(app,/response_format:'b64_json'/);
assert.match(app,/gemini-3\.1-flash-image-preview/);
assert.match(app,/gemini-3-pro-image-preview/);

assert.match(account,/启用图片生成/);
assert.match(account,/图片中转站/);
assert.match(account,/图片生成套餐/);
assert.match(account,/生成一张图片/);
assert.match(account,/function aiGenerateAccountImage\(\)/);
assert.match(account,/function aiImageReady\(\)/);
assert.match(account,/图片中转站尚未配置/);
assert.match(account,/图片双路线已启用/);
assert.match(account,/成功只扣一次，两条都失败才退点/);
assert.match(account,/图片生成每张固定扣20点/);
assert.match(account,/function aiShowPurchaseNotice\(\)/);
assert.match(account,/成功只扣一次20点/);
assert.match(account,/两条路线都失败则20点全额退回/);
assert.match(account,/更换浏览器或手机前请先备份并确认用户ID/);

assert.match(backend,/image: 20/);
assert.match(backend,/Deno\.env\.get\("IMAGE_MODEL"\) \|\| "gpt-image-2"/);
assert.match(backend,/function configuredImageRoutes\(\)/);
assert.match(backend,/IMAGE_ROUTE_2_BASE_URL/);
assert.match(backend,/IMAGE_ROUTE_2_API_KEY/);
assert.match(backend,/IMAGE_ROUTE_2_MODEL/);
assert.match(backend,/openai\("\/images\/generations"/);
assert.match(backend,/\[base \+ "\/v1" \+ path, base \+ path\]/);
assert.match(backend,/function relayImageResult\(data: any\)/);
assert.match(backend,/function guardedChatImagePrompt\(prompt: unknown, size: string, rolePhoto = false\)/);
assert.match(backend,/function shouldRetryImagePlain\(reason: string\)/);
assert.match(backend,/function shouldRetrySameImageRoute\(reason: string\)/);
assert.match(backend,/inlineData\?\.data/);
assert.match(backend,/fileData\?\.fileUri/);
assert.match(backend,/bareBase64\.length > 10000/);
assert.match(backend,/b64_json: bareBase64/);
assert.match(backend,/provider: "configured-relay"/);
assert.match(backend,/quality: "medium"/);
assert.match(backend,/response_format: "url"/);
assert.match(backend,/if \(\/\^gpt-image-2\$\/i\.test\(model\)\)/);
assert.match(backend,/content: guardedChatImagePrompt\(rawPrompt, size, rolePhoto\)/);
assert.match(backend,/name: "route-1",[\s\S]*base: base2,[\s\S]*timeoutMs: 150000/);
assert.match(backend,/\.\.\.original,[\s\S]*name: "route-2",[\s\S]*timeoutMs: 90000/);
assert.match(backend,/const chatTimeout = route\.timeoutMs \|\| 90000/);
assert.match(backend,/upstream = await openai\("\/chat\/completions", chatBody, chatTimeout, route\)/);
assert.match(backend,/richBody, 120000, route\)/);
assert.match(backend,/\}, 120000, route\)/);
assert.match(backend,/function recoverStalePendingCharges\(/);
assert.match(backend,/stale-pending-auto-refund/);
assert.match(backend,/await recoverStalePendingCharges\(userId, clientSecret\)/);
assert.match(backend,/image_routes: configuredImageRoutes\(\)\.filter/);
assert.match(backend,/await refund\(userId, clientSecret, "image", c\.cost, c\.ledgerId, reason\)/);
assert.match(backend,/refunded: c\.cost/);
assert.match(backend,/billed: false/);
assert.doesNotMatch(backend,/OPENAI_IMAGE_API_KEY/);
assert.doesNotMatch(backend,/https:\/\/api\.openai\.com\/v1\/images\/generations/);

assert.match(setup,/OPENAI_API_KEY=你的聊天\/识图中转站 key/);
assert.match(setup,/IMAGE_MODEL=gpt-image-2/);
assert.match(setup,/IMAGE_ROUTE_2_BASE_URL=备用中转站地址/);
assert.match(setup,/任一路线成功就只结算一次，全部尝试都失败才全额退点/);
assert.match(setup,/不需要额外配置官方 OpenAI Key/);

assert.match(account,/点数不足提醒/);
assert.match(account,/function aiCheckLowBalance\(balance\)/);
assert.match(account,/lowBalanceThreshold/);
assert.match(account,/AI点数快用完了/);

console.log('AI image account tests passed');
